// Copyright 2026, G2-on-Linux project
// SPDX-License-Identifier: BSL-1.0
/*!
 * @file
 * @brief Loader for binary .replay fixtures: REAL recorded controller sessions
 *        (raw IMU + the world optical poses fed to the fusion), used by the
 *        kalman-fusion real-data corpus test. Decoupled by construction — the
 *        inputs are recorded from hardware, never synthesised from the filter's
 *        own model. Generated by tools/telemetry/make_replay_fixture.py.
 *
 * Format (little-endian): magic "G2RP", u32 version=1, u32 n_imu, u32 n_pose,
 * then n_imu * {i64 t_ns; f32 ax,ay,az,gx,gy,gz}, then n_pose * {i64 t_ns; f32
 * px,py,pz,qx,qy,qz,qw}. Fields are read in groups so on-disk packing does not
 * depend on C struct padding.
 */
#pragma once

#include <algorithm>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <string>
#include <vector>

namespace g2replay {

struct Imu
{
	int64_t t_ns;
	float ax, ay, az, gx, gy, gz;
};
struct Pose
{
	int64_t t_ns;
	float px, py, pz, qx, qy, qz, qw;
};
struct Dataset
{
	std::string name;
	std::vector<Imu> imu;
	std::vector<Pose> pose;
};

//! Load one .replay fixture. Returns false on a missing/corrupt/wrong-version file.
inline bool
load(const std::string &path, Dataset &out)
{
	FILE *f = std::fopen(path.c_str(), "rb");
	if (f == nullptr) {
		return false;
	}
	char magic[4] = {0};
	uint32_t ver = 0, n_imu = 0, n_pose = 0;
	bool ok = std::fread(magic, 1, 4, f) == 4 && std::memcmp(magic, "G2RP", 4) == 0 &&
	          std::fread(&ver, 4, 1, f) == 1 && std::fread(&n_imu, 4, 1, f) == 1 &&
	          std::fread(&n_pose, 4, 1, f) == 1 && ver == 1;
	if (ok) {
		out.imu.resize(n_imu);
		out.pose.resize(n_pose);
		out.name = std::filesystem::path(path).stem().string();
		for (uint32_t i = 0; i < n_imu && ok; i++) {
			Imu &r = out.imu[i]; // t_ns then the 6 contiguous float members
			ok = std::fread(&r.t_ns, 8, 1, f) == 1 && std::fread(&r.ax, 4, 6, f) == 6;
		}
		for (uint32_t i = 0; i < n_pose && ok; i++) {
			Pose &r = out.pose[i];
			ok = std::fread(&r.t_ns, 8, 1, f) == 1 && std::fread(&r.px, 4, 7, f) == 7;
		}
	}
	std::fclose(f);
	return ok;
}

//! Enumerate the *.replay fixtures in @p dir (sorted). Empty if the dir is absent.
inline std::vector<std::string>
list_fixtures(const std::string &dir)
{
	std::vector<std::string> out;
	std::error_code ec;
	for (auto it = std::filesystem::directory_iterator(dir, ec);
	     !ec && it != std::filesystem::directory_iterator(); it.increment(ec)) {
		if (it->is_regular_file(ec) && it->path().extension() == ".replay") {
			out.push_back(it->path().string());
		}
	}
	std::sort(out.begin(), out.end());
	return out;
}

} // namespace g2replay
